Sprint3 pull-request
Iker-elorrieta/ADT2 pull request #3
Opened 2021-11-09 08:31 UTC by ALasherasSus

2021-11-09 12:37 UTC, Iker-elorrieta requested changes
Falta la búsqueda por páginas, altura...
Hay test que fallan y no deberían. Todos deben dar ok, aunque se busque un error.

2021-11-09 12:37 UTC, Iker-elorrieta commented on src/biblioteca/Libreria.java
> +		System.out.println("Introduce una Sentencia: (Ejm.:[T@-\"T�tulo\"]-[E@-\"Editorial\"]-[I@-\"ISBN\"]-[M@-\"Materia\"])");
Habrá que ampliar a TODOS los atributos del libro.

2021-11-09 12:37 UTC, Iker-elorrieta commented on src/biblioteca/Libreria.java
> +		ArrayList<Libro> libAux = new ArrayList<Libro>();
Combina todos los patrones?

2021-11-12 11:04 UTC, ALasherasSus commented on src/biblioteca/Libreria.java
> +		ArrayList<Libro> libAux = new ArrayList<Libro>();
Si, se pueden combinar

2021-11-16 07:51 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/141942705-3b5368a1-5419-4d11-9481-96a31747dae6.png)
Fallo con los números.
![image](https://user-images.githubusercontent.com/71759245/141943138-ed0e09d6-030c-43fc-8806-9d7c2aa0be70.png)
Encuentra más de lo deseado.

2021-11-16 08:45 UTC, Iker-elorrieta requested changes
![image](https://user-images.githubusercontent.com/71759245/141952262-85f5049b-0253-41d3-b341-31ec0ea74c4b.png)
En la combinación de resultados, duplica lo encontrado.

2021-11-16 09:06 UTC, Iker-elorrieta approved these changes

2021-11-16 09:06 UTC, merged